version: '3.8'

services:
  morpheus-compare:
    build:
      context: ..
      dockerfile: morpheus_js/Dockerfile.compare
    container_name: morpheus-compare
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: ["-L"]
    stdin_open: true
    tty: true
