#!/bin/sh

# Set these paths appropriately

BIN=./bin
CMD=./cmd
LIB=./lib

TAGGER=${BIN}/rft-annotate
TOKENIZER=${CMD}/tokenize.perl
ABBR_LIST=${LIB}/slovak-abbreviations
PARFILE=${LIB}/slovak.par

$TOKENIZER -a $ABBR_LIST $* |
perl -e 'while(<>){print; print "\n" if /^[.?\!]$/}' |
$TAGGER $PARFILE |
$CMD/lemma-lookup.perl lib/slovak-lemmas

