.TH rft-print 1 "September 2008" "" "RFT"
.SH NAME
rft-print \- prints a parameter file in human readable form
.SH SYNOPSIS
.B rft-print
.I parfile
.PP
.SH DESCRIPTION
.B rft-print
prints the contents of a parameter file of the RFTagger in
human-readable form to stdout.
.PP
.RE
.SH "EXIT STATUS"
.B rft-print
returns 0 unless some error occurs.
.SH "SEE ALSO"
rft-train rft-annotate
.SH AUTHOR
Helmut Schmid,
Institute for Computational Linguistics,
University of Stuttgart,
Email: schmid@ims.uni-stuttgart.de,
All Rights Reserved
